version: '3.1'

services:
  db: #database
    ports:
      - "5432:5432"
    image: postgres:11.5-alpine
    environment:
      POSTGRES_USER: property
      POSTGRES_PASSWORD: Property123
    volumes:
      - pgdata:/var/lib/postgres/data
volumes:
  pgdata: