info:
  title: A Property management application
  version: 1.0.0
  description: A PoC for future use
paths:
  '/properties/{id}':
    get:
      summary: Gets a property by id.
      parameters:
        - name: id
          in: path
          description: property ID
          required: true
          type: string
          minLength: 1
      responses:
        '200':
          description: Successful operation
          schema:
            $ref: '#/definitions/property'
  /properties:
    get:
      parameters:
        - name: since
          in: query
          type: integer
          format: int64
        - name: limit
          in: query
          type: integer
          format: int32
          default: 20
      responses:
        '200':
          description: list the property addresses
          schema:
            type: array
            items:
              $ref: '#/definitions/property'
        '500':
          description: server error
        default:
          description: generic error response
          schema:
            $ref: '#/definitions/error'
definitions:
  property:
    type: object
    properties:
      property_id:
        type: string
        minLength: 1
      street_number:
        type: string
        minLength: 1
      street:
        type: string
        minLength: 1
      street_suffix:
        type: string
        minLength: 1
      city:
        type: string
        minLength: 1
      state:
        type: string
        minLength: 1
      zip:
        type: string
        minLength: 1
      bedrooms:
        type: number
        format: float
      bathrooms:
        type: number
        format: float
      price:
        type: string
        minLength: 1
      real_estate_type:
        type: string
        minLength: 1
      property_type:
        type: string
        minLength: 1
      created_at:
        type: string
      square_feet:
        type: number
      description:
        type: string
      note:
        type: string
      images:
        type: array
        items:
          $ref: '#/definitions/Image'
  error:
    type: object
    required:
      - message
    properties:
      code:
        type: integer
        format: int64
      message:
        type: string
  Image:
    title: Image
    type: object
    properties:
      id:
        type: string
      title:
        type: string
      url:
        type: string
schemes:
  - http
produces:
  - application/json
consumes:
  - application/json
swagger: '2.0'
