swagger: "2.0"
info:
  description: A PoC for future use
  title: A Property management application
  version: 1.0.0
consumes:
  - application/json
produces:
  - application/json
schemes:
  - http
paths:
  /properties:
    get:
      parameters:
        - name: since
          in: query
          type: integer
          format: int64
        - name: limit
          in: query
          type: integer
          format: int32
          default: 20
      responses:
        200:
          description: list the property addresses
          schema:
            type: array
            items:
              $ref: "#/definitions/property"
        default:
          description: generic error response
          schema:
            $ref: "#/definitions/error"
        500:
          description: server error
definitions:
  property:
    type: object
    required:
      - address
    properties:
      id:
        type: integer
        format: int64
        readOnly: true
      address:
        type: string
        minLength: 1
      turn_key:
        type: boolean
      note:
        type: string
        minLength: 1
      bedrooms:
        type: integer
        format: int64
      bathrooms:
        type: integer
        format: int64
  error:
    type: object
    required:
      - message
    properties:
      code:
        type: integer
        format: int64
      message:
        type: string